### ISSUE TITLE
Incompatible with Towny

### ISSUE THREAD

**Issue by imsuiyue** [CoolLord22/OtherDrops#105]
**Describe the bug**
unable to perform custom drops when worked with Towny-0.96.2.0-for-1.12.2, everything drops as vanilla.

**To Reproduce**
1. break a customized block
2. See error

**Expected behavior**
custom drops

**Desktop (please complete the following information):**
 - OS: linux
 - Java Version 8
 - Server Version catserver 1.12
 - Plugin Version 3.2.7 Legacy

**Additional context**
[Server thread/ERROR] [Minecraft]: Could not pass event BlockBreakEvent to OtherDrops v3.2.7
java.lang.NoSuchMethodError: com.palmergames.bukkit.towny.utils.PlayerCacheUtil.getCachePermission(Lorg/bukkit/entity/Player;Lorg/bukkit/Location;Ljava/lang/Integer;Lcom/palmergames/bukkit/towny/object/TownyPermission$ActionType;)Z
	at com.gmail.zariust.otherdrops.event.DropRunner.checkIfNoPerms(DropRunner.java:395) ~[?:?]
	at com.gmail.zariust.otherdrops.event.DropRunner.run(DropRunner.java:101) ~[?:?]
	at com.gmail.zariust.otherdrops.SectionManager.scheduleDrop(SectionManager.java:420) ~[?:?]
	at com.gmail.zariust.otherdrops.SectionManager.performDrop(SectionManager.java:153) ~[?:?]
	at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:107) ~[?:?]
	at catserver.server.executor.asm.generated.GeneratedEventExecutor397.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-2a9163f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-2a9163f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-2a9163f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-2a9163f]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1200) [CraftEventFactory.class:git-CatServer-1.12.2-2a9163f]
	at catserver.server.CatServerEventHandler.onBlockBreak(CatServerEventHandler.java:30) [CatServerEventHandler.class:git-CatServer-1.12.2-2a9163f]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_CatServerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-2a9163f]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-2a9163f]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-2a9163f]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:835) [ForgeHooks.class:git-CatServer-1.12.2-2a9163f]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:356) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:304) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1083) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:771) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:625) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

defaults:
  world: world
  height: "<62"
otherdrops:
  COAL_ORE:
  - drop: nothing

**Comment by CoolLord22** [comment]
Hey! Thanks for the report, and sorry for so many label changes. I forgot that I actually removed the method you're receiving an error from in my own development branches of OtherDrops, as the blanket build check has been removed and is replaced by individual flags for each permission plugin (see below). 

I believe the issue is I never fully pushed these beta changes to the Discord server, I'll do that now and you can download the latest build there :)

If you wish to incorporate the build permission checking for Towny specifically, you can add

`flags: TOWNY_BUILD_PERMISSION` to your drop, and it will check whether the user is allowed to build. Let me know if you experience any further issues with this!

`flags.put("WORLDGUARD_BUILD_PERMISSION", WORLDGUARD_BUILD_PERMISSION);
		flags.put("TOWNY_BUILD_PERMISSION", TOWNY_BUILD_PERMISSION);
		flags.put("GRIEFPREVENTION_BUILD_PERMISSION", GRIEFPREVENTION_BUILD_PERMISSION);`

**Comment by CoolLord22** [comment]
Closing as OtherDropsLegacy-b32.jar should patch above issues.
